resources:
- repo: self

variables:
  container_registry: '{{cookiecutter.AZURE_CONTAINER_REGISTRY}}'
  azure_subscription: '{{cookiecutter.SUBSCRIPTION_ID}}'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '**{{cookiecutter.PROJECT_NAME_SLUG}}/agogosml'
    - '**{{cookiecutter.PROJECT_NAME_SLUG}}/input_reader'
    - '**{{cookiecutter.PROJECT_NAME_SLUG}}/output_writer'

jobs:
- job: Phase_1
  displayName: Agogosml-Build-CI
  condition: succeeded()

  steps:
  - bash: |
      if [ -z "$(azure_subscription)" ]; then
        echo "azure_subscription not set in variables - exiting"
        exit 1
      else
        echo "using azure_subscription - $(azure_subscription)"
      fi

    displayName: 'verify YAML variable set for azure_subscription'

  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      dockerFile: '**{{cookiecutter.PROJECT_NAME_SLUG}}/agogosml/Dockerfile.agogosml'
      imageName: 'agogosml:$(Build.BuildId)'

  - bash: |  
      echo "Since this is a merge build, we are creating a new 'latest' tag"
      docker tag $(container_registry)/agogosml:$(Build.BuildId) $(container_registry)/agogosml:latest

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as "latest" tag'

  - task: Docker@1
    displayName: 'Push base image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      command: 'Push an image'
      imageName: agogosml


- job: Phase_2
  displayName: InputReader-Build-CI
  dependsOn: Phase_1
  condition: succeeded()

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      dockerFile: '**{{cookiecutter.PROJECT_NAME_SLUG}}/input_reader/Dockerfile.input_reader'
      arguments: '--build-arg CONTAINER_REG=$(container_registry)/ --build-arg AGOGOSML_TAG=$(Build.BuildId)'
      imageName: 'input_reader:$(Build.BuildId)'

  - bash: |
      echo "Since this is a merge build, we are creating a new 'latest' tag"
      docker tag $(container_registry)/input_reader:$(Build.BuildId) $(container_registry)/input_reader:latest

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as "latest" tag'

  - task: Docker@1
    displayName: 'Push input reader app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      command: 'Push an image'
      imageName: 'input_reader'


- job: Phase_3
  displayName: OutputWriter-Build-CI
  dependsOn: Phase_1
  condition: succeeded()

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      dockerFile: '**{{cookiecutter.PROJECT_NAME_SLUG}}/output_writer/Dockerfile.output_writer'
      arguments: '--build-arg CONTAINER_REG=$(container_registry)/ --build-arg AGOGOSML_TAG=$(Build.BuildId)'
      imageName: 'output_writer:$(Build.BuildId)'

  - bash: |
      echo "Since this is a merge build, we are creating a new 'latest' tag"
      docker tag $(container_registry)/output_writer:$(Build.BuildId) $(container_registry)/output_writer:latest

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as "latest" tag'

  - task: Docker@1
    displayName: 'Push output writer app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      command: 'Push an image'
      imageName: 'output_writer'
