resources:
- repo: self

variables:
- group: azure-subscription-1

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '{{cookiecutter.PROJECT_NAME_SLUG}}/{{cookiecutter.PROJECT_NAME_SLUG}}'
    
jobs:
- job: Phase_1
    
  steps:
  - bash: |
      if [ -z "$(azure_subscription)" ]; then
        echo "azure_subscription not set in variables - exiting"
        exit 1
      else
        echo "using azure_subscription - $(azure_subscription)"
      fi

    displayName: 'verify YAML variable set for azure_subscription'
    
  - task: Docker@1
    displayName: 'Build app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      dockerFile: '**{{cookiecutter.PROJECT_NAME_SLUG}}/{{cookiecutter.PROJECT_NAME_SLUG}}/Dockerfile.{{cookiecutter.PROJECT_NAME_SLUG}}'
      arguments: '--build-arg CONTAINER_REG=$(container_registry)/ --build-arg AGOGOSML_TAG=$(Build.BuildId)'
      buildContext: '{{cookiecutter.PROJECT_NAME_SLUG}}/{{cookiecutter.PROJECT_NAME_SLUG}}'
      imageName: '{{cookiecutter.PROJECT_NAME_SLUG}}:$(Build.BuildId)'

  - bash: |
      echo "Since this is a merge build, we are creating a new 'latest' tag"
      docker tag $(container_registry)/{{cookiecutter.PROJECT_NAME_SLUG}}:$(Build.BuildId) $(container_registry)/{{cookiecutter.PROJECT_NAME_SLUG}}:latest

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as "latest" tag'


  - task: Docker@1
    displayName: 'Push app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      command: 'Push an image'
      imageName: '{{cookiecutter.PROJECT_NAME_SLUG}}'
