resources:
- repo: self

variables:
- group: azure-subscription-1
- name: project_name
  value: '{{cookiecutter.PROJECT_NAME_SLUG}}'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '$(project_name)/$(project_name)'
    
jobs:
- job: Phase_1
    
  steps:
  - bash: |
      if [ -z "$(azure_subscription)" ]; then
        echo "azure_subscription not set in variables - exiting"
        exit 1
      else
        echo "using azure_subscription - $(azure_subscription)"
      fi

    displayName: 'verify YAML variable set for azure_subscription'
    
  - task: Docker@1
    displayName: 'Build app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      dockerFile: '**$(project_name)/$(project_name)/Dockerfile.$(project_name)'
      arguments: '--build-arg CONTAINER_REG=$(container_registry)/ --build-arg AGOGOSML_TAG=$(Build.BuildId)'
      buildContext: '$(project_name)/$(project_name)'
      imageName: '$(project_name):$(Build.BuildId)'

  - bash: |
      echo "Since this is a merge build, we are creating a new 'latest' tag"
      docker tag $(container_registry)/$(project_name):$(Build.BuildId) $(container_registry)/$(project_name):latest

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Tag as "latest" tag'


  - task: Docker@1
    displayName: 'Push app image'
    inputs:
      azureSubscriptionEndpoint: $(azure_subscription)
      azureContainerRegistry: $(container_registry)
      command: 'Push an image'
      imageName: '$(project_name)'
