version: "3"

services:
  input-adapter:
    build: ../src/instance-app/
    image: agogosacr.azurecr.io/instance-app:${TAG}
    ports: 
      - '5000:5000'
    expose:
      - '5000'
    networks:
      mynet:
        aliases:
          - instance-app.agogosml.com

networks:
  mynet:
    driver: bridge