{{ $fullname := include "data-pipeline-app.cli.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.cli.service.type }}
  ports:
    - port: {{ .Values.cli.service.externalPort }}
      targetPort: {{ .Values.cli.service.internalPort }}
      protocol: TCP
      name: {{ .Values.cli.name | replace "_" "-" }}
  selector:
    app: {{ $fullname }}
