{{ $fullname := include "data-pipeline-app.instance-app.fullname" . }}
# For each instance app, we create its own service
{{- $root := . -}}
{{- range $index, $value := .Values.instance_apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ .name | replace "_" "-" }}-{{ $index }}
  labels:
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}"
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ $fullname }}-{{ .name | replace "_" "-" }}
    deployment: {{ .deployment }}
---
{{- end }}