# For each instance app, we create its own service
{{- $root := . -}}
{{- range $index, $value := .Values.instance_apps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name | replace "_" "-" }}-{{ $index }}-config
  namespace: default
data:
{{- range $key, $value := .env }}
  {{ $key }}:{{ $value }}
{{- end }}
---
{{- end }}