version: '2.2'
services:
  app:
    build: .
    environment:
      - MODE=dev
      - KAFKA_HOST=127.0.0.1
      - KAFKA_PORT=9092
      - ZOOKEEPER_HOST=127.0.0.1
      - ZOOKEEPER_PORT=2181
    depends_on:
      - kafka


  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    environment:
      - ADVERTISED_HOST=127.0.0.1
      - ADVERTISED_PORT=9092
    ports:
      - 9092:9092
      - 2181:2181
    networks:
      - kafkanet


networks:
  kafkanet: