ARG CONTAINER_REG
ARG AGOGOSML_TAG="latest"

FROM ${CONTAINER_REG}agogosml/agogosml:${AGOGOSML_TAG} as builder

WORKDIR /usr/src/agogosml
COPY ./input_reader ./input_reader

# Release
FROM ${CONTAINER_REG}agogosml/agogosml:${AGOGOSML_TAG} AS input_reader

WORKDIR /input_reader
COPY --from=builder /usr/src/agogosml/input_reader /input_reader

CMD ["python", "main.py"]
