# Default values for agogosml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: "library"
imagePullSecret: "acr-auth"

namespace: default

input_reader:
  name: input_reader
  # tag: 
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  env:
    MESSAGING_TYPE: "AAA"
    AZURE_STORAGE_ACCOUNT: ""
    AZURE_STORAGE_ACCESS_KEY: ""
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    LEASE_CONTAINER_NAME: ""
    APP_HOST: ""
    APP_PORT: ""
    KAFKA_TOPIC: ""
    KAFKA_CONSUMER_GROUP: ""
    APP_HOST: ""
    APP_PORT: ""
    KAFKA_ADDRESS: ""

output_writer:
  name: redis
  tag: alpine
  imagePullPolicy: IfNotPresent
  env:
    MESSAGING_TYPE: ""
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    KAFKA_TOPIC: ""
    KAFKA_ADDRESS: ""
    OUTPUT_WRITER_PORT: ""

instance_apps:
  - name: nginx
    tag: stable
    imagePullPolicy: IfNotPresent
    deployment: "green"
    service:
      type: ClusterIP
      externalPort: 5000
      internalPort: 5000

  # Example of multiple apps
  - name: nginx
    tag: stable
    imagePullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalPort: 5000
      internalPort: 5000
    deployment: "blue"