ARG PYTHON_VERSION=3.7

FROM python:${PYTHON_VERSION} AS builder

WORKDIR /src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip wheel --no-cache-dir -r requirements.txt -w /deps

COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

RUN flake8 *.py \
 && pydocstyle *.py \
 && python -m doctest *.py

FROM python:${PYTHON_VERSION}-slim AS runtime

WORKDIR /{{cookiecutter.PROJECT_NAME_SLUG}}/deps
COPY --from=builder /deps .
RUN pip install --no-cache-dir *.whl

WORKDIR /{{cookiecutter.PROJECT_NAME_SLUG}}/src
COPY --from=builder /src .

ENV HOST=0.0.0.0
ENV PORT=80
ENV WORKERS=4
ENV LOG_LEVEL=info

EXPOSE $PORT

CMD gunicorn --log-level="$LOG_LEVEL" --bind="$HOST:$PORT" --workers="$WORKERS" "main:build_app(wsgi=True)"
