{{ $fullname := include "data-pipeline-app.input_reader.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ quote .Release.Name }}
    heritage: {{ quote .Release.Service }}
spec:
  replicas: {{ .Values.input_reader.replicaCount }}
  selector:
    matchLabels:
      app: {{ quote $fullname }}
  template:
    metadata:
      labels:
        app: {{ quote $fullname }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.registry }}/{{ .Values.input_reader.name }}:{{ default "latest" .Values.input_reader.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.input_reader.pullPolicy }}
          envFrom:
          - configMapRef:
              name: input-reader-{{ .Values.input_reader.tag }}-config
      {{ if .Values.registry }}imagePullSecrets:
        - name: {{ .Values.imagePullSecret}}{{ end }}