{{ $configName := include "data-pipeline-app.output-writer.config-name" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
data:
  MESSAGING_TYPE: {{ quote .Values.output_writer.env.MESSAGING_TYPE }}
  EVENT_HUB_NAMESPACE: {{ quote .Values.output_writer.env.EVENT_HUB_NAMESPACE }}
  EVENT_HUB_NAME: {{ quote .Values.output_writer.env.EVENT_HUB_NAME }}
  EVENT_HUB_SAS_POLICY: {{ quote .Values.output_writer.env.EVENT_HUB_SAS_POLICY }}
  EVENT_HUB_SAS_KEY: {{ quote .Values.output_writer.env.EVENT_HUB_SAS_KEY }}
  KAFKA_TOPIC: {{ quote .Values.output_writer.env.KAFKA_TOPIC }}
  KAFKA_ADDRESS: {{ quote .Values.output_writer.env.KAFKA_ADDRESS }}
  OUTPUT_WRITER_PORT: {{ quote .Values.output_writer.env.OUTPUT_WRITER_PORT }}