{{ $configName := include "data-pipeline-app.output-writer.config-name" . }}
{{- $root := . -}}
{{- range $appName, $value := .Values.instance_apps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}-{{ $appName | replace "_" "-" }}
data:
  MESSAGING_TYPE: {{ quote $value.output_writer.env.MESSAGING_TYPE }}
  EVENT_HUB_NAMESPACE: {{ quote $value.output_writer.env.EVENT_HUB_NAMESPACE }}
  EVENT_HUB_NAME: {{ quote $value.output_writer.env.EVENT_HUB_NAME }}
  EVENT_HUB_SAS_POLICY: {{ quote $value.output_writer.env.EVENT_HUB_SAS_POLICY }}
  EVENT_HUB_SAS_KEY: {{ quote $value.output_writer.env.EVENT_HUB_SAS_KEY }}
  KAFKA_TOPIC: {{ quote $value.output_writer.env.KAFKA_TOPIC }}
  KAFKA_ADDRESS: {{ quote $value.output_writer.env.KAFKA_ADDRESS }}
  OUTPUT_WRITER_PORT: {{ quote $value.output_writer.env.OUTPUT_WRITER_PORT }}
---
{{- end }}