version: "3.7"

services:
    input-reader:
        image: ${CONTAINER_REG}/input_reader10:${TAG}
        networks:
            mynet:
                aliases:
                    - input
        environment:
            MESSAGING_TYPE: ${MESSAGING_TYPE}
            AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
            EVENT_HUB_NAMESPACE: ${EVENT_HUB_NAMESPACE}
            EVENT_HUB_NAME: ${EVENT_HUB_NAME_INPUT}
            EVENT_HUB_SAS_POLICY: ${EVENT_HUB_SAS_POLICY}
            LEASE_CONTAINER_NAME: ${LEASE_CONTAINER_NAME_INPUT}
            APP_HOST: sample
            APP_PORT: 3000
            AZURE_STORAGE_ACCESS_KEY:
            EVENT_HUB_SAS_KEY: ${EVENT_HUB_SAS_KEY_INPUT}
            #kafka 
            KAFKA_TOPIC_INPUT: ${KAFKA_TOPIC_INPUT}
            KAFKA_TIMEOUT: ${KAFKA_TIMEOUT}
            KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
            KAFKA_ADDRESS: ${KAFKA_ADDRESS}
            EVENTHUB_KAFKA_CONNECTION_STRING: ${EVENTHUB_KAFKA_CONNECTION_STRING}

    output-writer:
        image: ${CONTAINER_REG}/output_writer10:${TAG}
        ports:
            - "127.0.0.1:6000:6000"
        networks:
            mynet:
                aliases:
                    - output
        environment:
            MESSAGING_TYPE: ${MESSAGING_TYPE}
            AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
            AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}
            LEASE_CONTAINER_NAME: ${LEASE_CONTAINER_NAME_OUTPUT}
            EVENT_HUB_NAMESPACE: ${EVENT_HUB_NAMESPACE}
            EVENT_HUB_NAME: ${EVENT_HUB_NAME_OUTPUT}
            EVENT_HUB_SAS_POLICY: ${EVENT_HUB_SAS_POLICY}
            OUTPUT_WRITER_PORT: 6000
            OUTPUT_WRITER_HOST: output
            EVENT_HUB_SAS_KEY: ${EVENT_HUB_SAS_KEY_OUTPUT}
            #kafka             
            KAFKA_TOPIC_OUTPUT: ${KAFKA_TOPIC_OUTPUT}
            KAFKA_TIMEOUT: ${KAFKA_TIMEOUT}
            KAFKA_ADDRESS: ${KAFKA_ADDRESS}
            EVENTHUB_KAFKA_CONNECTION_STRING: ${EVENTHUB_KAFKA_CONNECTION_STRING}

            
    sample-app:
        image: ${CONTAINER_REG}/sample_app10:${APP_TAG}
        ports:
            - "127.0.0.1:3000:3000"
        networks:
            mynet:
                aliases:
                    - sample
        environment:
            HOST: 0.0.0.0
            PORT: 3000
            OUTPUT_URL: http://output:6000
            SCHEMA_FILEPATH: schema_example.json
            MODEL_PATH: /temp/assets/sample_model.zip

networks:
    mynet: