{{ $configName := include "data-pipeline-app.output-writer.config-name" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
data:
{{- range $key, $value := .Values.output_writer.env }}
  {{ $key }}: {{ quote $value }}
{{- end }}
