#!/bin/bash

export ARM_SUBSCRIPTION_ID=[CENSORED]
export ARM_CLIENT_ID=[CENSORED]
export ARM_CLIENT_SECRET=[CENSORED]
export ARM_TENANT_ID=[CENSORED]
export ARM_ENVIRONMENT=public

export STORAGE_ACCOUNT_NAME=[CENSORED]
export ARM_ACCESS_KEY=[CENSORED]

